name: Hello World Workflow

on:
  push:  # Déclenche le workflow lorsqu'un push est effectué
    branches:
      - main  # Limité aux pushes sur la branche 'main'

  pull_request:  # Déclenche le workflow lorsqu'une pull request est ouverte ou mise à jour
    branches:
      - main  # Limité aux pull requests ciblant la branche 'main'

jobs:
  greeting:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu

    steps:
      - name: Checkout code  # Étape pour récupérer le code source du dépôt
        uses: actions/checkout@v3

      - name: Print Hello World  # Étape pour afficher "Hello World" dans les logs
        run: echo "Hello World"
