name: Hello World Workflow

on:
  push:
    branches:
      - main  # Le workflow s'exécute lorsqu'un push est effectué sur la branche 'main'

jobs:
  greeting:  # Nom du job
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu

    steps:
      - name: Checkout code  # Étape pour récupérer le code source du dépôt
        uses: actions/checkout@v3

      - name: Print Hello World  # Ét
